### ISSUE TITLE
Options for running integration tests & unit tests seperatly

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-parent#115]
For CI purposes, it's preferable to run ITs as a separate task. 
For example:

```
mvn verify -PonlyITs # skips unit tests
mvn verify -PonlyUTs # skips integration tests 
```
Only ability to skip UTs is needed at this point, but having both is good for consistency

**Comment by yegor256** [comment]
@andreoss I believe you can do it with `-DskipTests` and `-Dfailsafe.skip` (or something similar)

**Comment by andreoss** [comment]
@yegor256 The problem is that `-DskipTests` skips both, and `-DskipITs` skips only ITs.
https://stackoverflow.com/questions/46712510/how-to-skip-surefire-tests-but-run-failsafe-tests
