### ISSUE TITLE
antrun xcop should ignore target/

### ISSUE THREAD

**Issue by victornoel** [jcabi/jcabi-parent#116]
I am trying to use the maven-shade-plugin in cactoos-matches and because this plugin generates a new pom.xml file that it stores in the target dorectory, the xcop execution by antrun fails since it is not formatted as expected.

I believe we should not run any check at all on the content of the target directory and have antrun focus on the actual sources of the project.

**Comment by victornoel** [comment]
ha, my bad, actually, the problem is that maven-shade-plugin generates the file in the source directory itself :)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#116` is not assigned, can't get performer
