### ISSUE TITLE
jcabi-log dependencies confilict for slf4j

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-parent#124]
011f5aa uses older version of `slf4-log4j` , incompatible with `slf4j-api` version `jcabi-log` currently has 

https://github.com/jcabi/jcabi-log/blob/master/pom.xml#L81

Proposal:
1) `jcabi-parent` should handle `slf4j-api` version 
2) `jcabi-parent` should not bring any implementations of `slf4j`

**Comment by yegor256** [comment]
@rultor release, tag is `0.55.0`

**Comment by yegor256** [comment]
@andreoss this one should be good
