### ISSUE TITLE
Avoid using -Werror

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-parent#132]
This line is impossible to redefine by child pom without copying all compiler arguments 
https://github.com/jcabi/jcabi-parent/blob/master/pom.xml#L1695

Instead of using `-Werror`, this option should be used
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#failOnWarning

**Comment by yegor256** [comment]
@rultor release, tag is `0.57.2`

**Comment by yegor256** [comment]
@andreoss thanks!
