### ISSUE TITLE
junit-bom scope mistake

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-parent#140]

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.3`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#140` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.4`
