### ISSUE TITLE
Upgrade qulice-maven-plugin to 0.12

### ISSUE THREAD

**Issue by alevohin** [jcabi/jcabi-parent#16]
We need to upgrade qulice-maven-plugin to 0.12 to resolve the issue https://github.com/teamed/qulice/issues/366.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@maurezen it's your task, go ahead

**Comment by dmarkov** [comment]
@alevohin thank you for the ticket reported, I topped your account for 15 mins, transaction `49978505`

**Comment by maurezen** [comment]
Created a pull request here #18

**Comment by maurezen** [comment]
@dmarkov could you please find someone to review the pull request #18 ? It's been almost 48h since I created it.

**Comment by maurezen** [comment]
@alevohin pull request #18 merged, please close the issue.

**Comment by alevohin** [comment]
@maurezen could you make release/deploy?

**Comment by maurezen** [comment]
@alevohin I believe that's something for @yegor256 to do.

**Comment by yegor256** [comment]
@rultor release, tag is `0.32`

**Comment by yegor256** [comment]
@alevohin version 0.32 is in Maven Central

**Comment by alevohin** [comment]
@maurezen @yegor256 thanks!

**Comment by dmarkov** [comment]
@maurezen thanks, I just added **30 mins** to your account, payment `50257021`... +30 added to your rating, current score is: [+390](http://www.netbout.com/b/35102?open=rating)
