### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-parent#17]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@romankisilenko it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmarkov** [comment]
@maurezen many thanks for the bug report, I added 15 mins to your acc, transaction `50043131`

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko Much obliged! I've added **30 mins** to your account in payment "50616180"... +30 added to your rating, current score is: +270
