### ISSUE TITLE
Qulice configuration is ignored in children

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-parent#19]
In children projects parent's qulice configuration is ignored. This leads to the bugs like jcabi/jcabi-email#11 and jcabi/jcabi-manifests#16. 

mvn help:effective-pom does list qulice configuration present.
mvn help:active-profiles does list qulice profile present.

mvn -X qulice:check -Pqulice lists the following:
>[DEBUG] Goal:          com.qulice:qulice-maven-plugin:0.10:check (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
< configuration>
  < asserts>${qulice.asserts}< /asserts>
  < excludes>${qulice.excludes}< /excludes>
  < license default-value="LICENSE.txt">${qulice.license}< /license>
  < skip default-value="false">${qulice.skip}< /skip>
  < project default-value="${project}"/>
  < session default-value="${session}"/>
< /configuration>

and

>[DEBUG] Configuring mojo 'com.qulice:qulice-maven-plugin:0.10:check' with basic configurator -->
[DEBUG]   '(s) asserts = []
[DEBUG]   '(s) excludes = []
[DEBUG]   '(s) license = LICENSE.txt
[DEBUG]   '(s) skip = false
[DEBUG]   '(s) project = MavenProject: com.jcabi:jcabi-manifests:2.0-SNAPSHOT @ %path to project%\jcabi-manifests\pom.xml
[DEBUG]   '(f) session = org.apache.maven.execution.MavenSession@6889634c
[DEBUG] -- end configuration --

**Comment by yegor256** [comment]
@maurezen that's true, we should move [these three lines](https://github.com/jcabi/jcabi-parent/blob/master/pom.xml#L236-L238) to the `<plugin>` section, thanks for reporting

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@marczeeee can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmarkov** [comment]
@maurezen thank you for the ticket reported, I topped your account for 15 mins, transaction `50302740`

**Comment by Marczeeee** [comment]
@maurezen Pull request #20 was merged. Please close this issue.

**Comment by dmarkov** [comment]
@marczeeee I added **30 mins** to your account, many thanks for working with the project!; added +30 to your rating, now it is equal to +90
