### ISSUE TITLE
Update jcabi-github version

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-parent#25]
Currently, we are specifying `jcabi-github` version `0.17` in `pom.xml`. This version of `jcabi-github` has a bug that prevents one of the mock classes, `MkStorage.Infile` from being instantiated, due to mutability issues (see https://github.com/jcabi/jcabi-github/issues/934). This effectively prevents the usage of the entire mock unit testing framework provided by `jcabi-github`.

Let's update this dependency to a later version, at least `0.18.3`, which fixes this bug. Preferably a later version (current is `0.21.3`). See https://github.com/jcabi/jcabi-github/releases for the list of releaes.

**Comment by dmarkov** [comment]
I will ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@carlosmiranda thanks for reporting! I topped your account for 15 mins, transaction 53408400

**Comment by dmarkov** [comment]
@super132 the task is yours

**Comment by super132** [comment]
@carlosmiranda, PR #30 fixed this issue. Would you please close this ticket? Thanks.

**Comment by carlosmiranda** [comment]
@super132 Thank you very much!

**Comment by super132** [comment]
@dmarkov could you please share the payment details? Thanks.

**Comment by dmarkov** [comment]
@super132 **38 mins** was added to your account, many thanks for your contribution! The task took AP-3M553007YY389061X.... the bonus for fast delivery (m=2903)... added +38 to your rating, now it is equal to [+181](http://www.netbout.com/b/35282?open=rating)
