### ISSUE TITLE
buildnumber-maven-plugin should run before at process-resources phase

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-parent#37]
There is at least one instance when we need the build number during the source-processing phase: in jcabi-aspects we process sources in order to insert project version and build number right into sources.

I think that `buildnumber-maven-plugin`'s phase should be changed from `process-resources` to `process-sources` or even to `initialize`, because `process-resources` happens later in the default lifecycle than the other two.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@Suseika fixed in 57506cd thanks
