### ISSUE TITLE
Can we remove the dependency on antlr-annotations?

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-parent#38]
It is not used anymore by antlr4: the last `antlr-runtime` version 4.5 removed it:

https://github.com/antlr/antlr4/releases/tag/4.5

> Be aware that we no longer deploy a maven antlr4-annotations artifact and in fact we no longer use Java annotations in the Java runtime and so that code is disappeared.

Other reasons to remove it:

- antlr4-annotations doesn't support JDK>1.6.
- If antlr-annotations is present in the parent pom of a project that uses antlr4-runtime>4.3, then qulice will fail the build due to duplicated classes.

It would also be nice to increase the version of `antlr-maven-plugin` to 4.5 or 4.5.1

**Comment by Suseika** [comment]
Here is the part of log where qulice finds duplicate classes if I use newer `antlr4-runtime`:
```
[INFO] Checking compile classpath
[WARNING] Found duplicate and different classes in [org.antlr:antlr4-annotations:4.3,org.antlr:antlr4-runtime:4.5.1] :
[WARNING]   org.antlr.v4.runtime.misc.NotNull
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.35`

**Comment by Suseika** [comment]
@yegor256 Thanks!
