### ISSUE TITLE
Exclude hamcrest-core from mockito-core dependency

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-parent#39]
Currently, we have a dependency on the mockito-core:1.9.5 which depends on hamcrest-core:1.1
Under certain circumstances this might cause dependency collisions
(https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/)
We should exclude hamcrest-core from mockito-core.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by oruam85** [comment]
@yegor256 @dmarkov i can take this task. Let me know your answer

**Comment by yegor256** [comment]
@longtimeago we do exclude mockito-core already: https://github.com/jcabi/jcabi-parent/blob/0.35/pom.xml#L1352-L1367 Or I missed something?

**Comment by longtimeago** [comment]
@yegor256 what about jcabi-junit profile?

**Comment by yegor256** [comment]
@longtimeago the "exclusion" works in/for all profiles

**Comment by longtimeago** [comment]
@yegor256 than the issue is invalid. Thanks!
