### ISSUE TITLE
parallel execution of surefire tests

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-parent#4]
Let's add such configuration to `pom.xml`

**Comment by alxn** [comment]
@yegor256 what's the best way to disable parallel running, probably in the pom that is including the jcabi parent? At a class level with a Junit annotation would also be interesting.

**Comment by yegor256** [comment]
@alxn like this:

```xml
<configuration>
  <parallel>none</parallel>
</configuration>
```

**Comment by alxn** [comment]
Ah thanks, I'd finally come up with:

```xml
                <configuration combine.self="override">
```

 - after playing with `mvn help:effective-pom`

I first went to their doc, and they said:

> The most obvious one is by using the parallel parameter. The possible values depend on the test 
> provider used. For JUnit 4.7 and onwards, this may be methods, classes, both, suites, 
> suitesAndClasses, suitesAndMethods, classesAndMethods or all.

No hint of "none" !! :frowning:

**Comment by yegor256** [comment]
@alxn yeah, sorry about that :)
