### ISSUE TITLE
Don't use repositories element in the pom.

### ISSUE THREAD

**Issue by Rotwang** [jcabi/jcabi-parent#40]
Hi,

parent pom contains a repositories element which forces maven to look for artifacts in an external repository:

```xml
    <repositories>
        <!--
        You should keep it empty in your project.
        @see http://www.sonatype.com/people/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/
        -->
        <repository>
            <id>oss.sonatype.org</id>
            <url>https://oss.sonatype.org/content/groups/public</url>
        </repository>
    </repositories>
```

There are workarounds for this issue, however it would be better if the repository resolution stuff was left over for the settings.xml to handle.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Rotwang make sense, thanks for reporting

**Comment by yegor256** [comment]
@Rotwang fixed in 0e25cca

**Comment by yegor256** [comment]
@rultor release, tag is `0.36`

**Comment by yegor256** [comment]
@Rotwang new version 0.36 is in Maven Central. please close the ticket if you're happy :)

**Comment by Rotwang** [comment]
Thank you!
