### ISSUE TITLE
Downgrade cobertura-maven-plugin to 2.6

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-parent#43]
During the work on https://github.com/teamed/xockets-hadoop-transport/issues/1086
We've faced with a bug cobertura/cobertura#230
It prevents "site" profile (defined in a parent pom) to work properly.
```
java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
```
I propose to downgrade cobertura-maven-plugin to 2.6 in a parent pom

**Comment by longtimeago** [comment]
@yegor256 can we do this downgrade?

**Comment by yegor256** [comment]
@longtimeago check  2ed44fa. correct?

**Comment by longtimeago** [comment]
@yegor256 perfect, thanks!

**Comment by longtimeago** [comment]
@yegor256 please, release a new version of parent pom

**Comment by yegor256** [comment]
@rultor release, tag is `0.38`

**Comment by longtimeago** [comment]
@yegor256 thank you!
