### ISSUE TITLE
Upgrade to new hamcrest

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-parent#45]
There is new version of hamcrest library available:

```
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>java-hamcrest</artifactId>
    <version>2.0.0.0</version>
</dependency>
```

Notice, that they changed the artifactId.
Please upgrade parent to the above new hamcrest version.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@krzyk we have two deps now:

```
                <dependency>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-library</artifactId>
                    <scope>test</scope>
                </dependency>
```

We should replace them both with this new one?

**Comment by krzyk** [comment]
@yegor256 looks like the new hamcrest has only two java related projects: java-hamcrest and junit-hamcrest (this one we don't use, it was already in 1.x versions). From the packages it looks like it is equivalent of hamcrest-all from 1.3. So we would need just the java-hamcrest instead of hamcrest-core and hamcrest-library.

**Comment by mkordas** [comment]
@yegor256 can we dispatch this issue? I would be interested in taking it.

**Comment by yegor256** [comment]
@krzyk already done
