### ISSUE TITLE
Upgrade to qulice 0.14

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-parent#46]
New version (`0.14`) of qulice has been released with few bug fixes, please upgrade parent pom to this new version.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@rultor release, tag is `0.40`

**Comment by yegor256** [comment]
@krzyk done, see 0.40
