### ISSUE TITLE
Wrong artifact: javax.servlet:servlet-api 3.0.1

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-parent#47]
In our current pom we have the following artifact defined:

```
<dependency>
	<groupId>javax.servlet</groupId>
	<artifactId>servlet-api</artifactId>
	<version>3.0.1</version>
</dependency>
```

This does not exist. The `servlet-api` artifact was renamed to `javax.servlet-api` for version 3.0.1 and above. It should be:

```
<dependency>
	<groupId>javax.servlet</groupId>
	<artifactId>javax.servlet-api</artifactId>
	<version>3.0.1</version>
</dependency>
```

See http://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/3.0.1

**Comment by carlosmiranda** [comment]
@yegor256 can you take a look at this; the bug breaks any project that tries to use version `0.40` without overriding this dependency.

**Comment by yegor256** [comment]
@carlosmiranda fixed, thanks

**Comment by yegor256** [comment]
@rultor release, tag is `0.40.1`
