### ISSUE TITLE
Update qulice

### ISSUE THREAD

**Issue by exper0** [jcabi/jcabi-parent#49]
jcabi-parent uses qulice version 0.14 but the latest version is 0.15.2. Let's update it

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@rultor release, tag is `0.41`

**Comment by yegor256** [comment]
@exper0 fixed, use 0.41
