### ISSUE TITLE
Remove XML exclude from Qulice

### ISSUE THREAD

**Issue by mkordas** [jcabi/jcabi-parent#50]
All XML files are excluded by default from Qulice check: https://github.com/jcabi/jcabi-parent/blob/0.40.1/pom.xml#L234

Majority of problems with Qulice's XML validation was solved recently and moreover in case of any problems XML check could be skipped for each project separately.

Let's remove that suppression.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mkordas fixed in 8273b7c thanks!
