### ISSUE TITLE
JSR-303 validator failed to initialize

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-parent#55]
While trying to figure out why I get in my project error of types:

- `JSR-303 validator failed to initialize: Unable to instantiate Configuration`
- `JSR-303 validator failed to initialize: HV000183: Unable to load 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead`

I realized that If I add the following dependency to the profile `jcabi-versionalize-packages` I don't have the errors anymore
```
<dependencies>
    <dependency>
       <groupId>javax.el</groupId>
       <artifactId>javax.el-api</artifactId>
       <version>3.0.1-b04</version>
       <scope>runtime</scope>
    </dependency>
</dependencies>
```
The complete profile is then:
```
        <profile>
            <!--
            For every Java package it creates a VERSION.txt file in
            "src/main/resources" directory. This is done in order to help
            with identification of currently used version of a package.
            -->
            <id>jcabi-versionalize-packages</id>
            <activation>
                <file>
                    <exists>${basedir}/src/main/java</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.jcabi</groupId>
                        <artifactId>jcabi-maven-plugin</artifactId>
                        <version>0.13.2</version>
                        <executions>
                            <execution>
                                <id>jcabi-versionalize-packages</id>
                                <goals>
                                    <goal>versionalize</goal>
                                </goals>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>javax.el</groupId>
                                <artifactId>javax.el-api</artifactId>
                                <version>3.0.1-b04</version>
                                <scope>runtime</scope>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
I don't know if it makes sense to modify it directly into the parent pom or if it should be fixed in` jcabi-maven-plugin` directly but in both cases a new release of the parent pom will be needed so I create the ticket and let you do what is the best.

**Comment by essobedo** [comment]
@yegor256 this is needed for xockets-xjm, thx in advance

**Comment by pinaf** [comment]
@yegor256 what do you think of this one?

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@essobedo the right way would be to fix `jcabi-maven-plugin`, since the bug is there. If someone will use that plugin somewhere else, outside of jcabi-parent, the bug will still show up. Can you please re-submit it to jcabi-maven-plugin repo?

**Comment by essobedo** [comment]
@yegor256 ok I will

**Comment by essobedo** [comment]
@yegor256 done here https://github.com/jcabi/jcabi-maven-plugin/issues/53

**Comment by yegor256** [comment]
@essobedo thanks

**Comment by pinaf** [comment]
@yegor256 could we also update jcabi-parent's `pom.xml` to use the new version of `jcabi-maven-plugin`?

**Comment by yegor256** [comment]
@rultor release, tag is `0.45`

**Comment by pinaf** [comment]
@yegor256 release failed :(

**Comment by yegor256** [comment]
@rultor release, tag is `0.45`

**Comment by pinaf** [comment]
@yegor256 failed again :(
>
Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.sink.impl.XhtmlBaseSink

**Comment by yegor256** [comment]
@pinaf hm... looks like this problem is related to this recent change I've made: 	5fa3faf

**Comment by yegor256** [comment]
@pinaf any thoughts?

**Comment by pinaf** [comment]
@yegor256 this seems to be the issue https://lists.apache.org/thread.html/%3CCAJmbs8hXju+9roV5VyEHte5vRWSeD8-t_HUyWmQM6JoK=hhhdA@mail.gmail.com%3E

**Comment by yegor256** [comment]
@rultor release, tag is `0.45`

**Comment by yegor256** [comment]
@pinaf version 0.45 is in Maven Central

**Comment by pinaf** [comment]
@yegor256 thanks!
