### ISSUE TITLE
Consider upgrading the third party libraries

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-parent#56]
Even with the latest version of the parent pom which is `0.43` while I'm creating this ticket, there are many third party libraries that could be upgraded.

Indeed if I launch the command `mvn versions:display-dependency-updates` I get the next output:

```
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.jcabi:jcabi-aspects ............................. 0.22.3 -> 0.22.4
[INFO]   com.jcabi:jcabi-dynamo ................................ 0.21 -> 0.21.1
[INFO]   com.jcabi:jcabi-email ..................................... 1.7 -> 1.8
[INFO]   com.jcabi:jcabi-s3 .................................. 0.11.4 -> 0.11.5
[INFO]   commons-collections:commons-collections ............ 3.2.2 -> 20040616
[INFO]   commons-io:commons-io ..................................... 2.4 -> 2.5
[INFO]   commons-net:commons-net ................................... 3.4 -> 3.5
[INFO]   org.antlr:antlr4-runtime ............................ 4.5.2-1 -> 4.5.3
[INFO]   org.apache.commons:commons-math3 ........................ 3.6 -> 3.6.1
[INFO]   org.mockito:mockito-core .................. 2.0.44-beta -> 2.0.53-beta
[INFO]   org.slf4j:slf4j-log4j12 ............................. 1.7.19 -> 1.7.21
[INFO]   xml-apis:xml-apis .................................... 1.4.01 -> 2.0.2
```

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by essobedo** [comment]
@yegor256 we need you here please

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 please dispatch this issue, I need it for a ticket of xockets-hadoop-transport

**Comment by essobedo** [comment]
@dmarkov @yegor256 we need to do something with it, either accept it or reject it but please let's do something

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@essobedo I upgraded versions in 8d44818 thanks!

**Comment by essobedo** [comment]
@yegor256 many thx, any idea when we can have a release with this fix?

**Comment by essobedo** [comment]
@yegor256 this fix is not really helping without a release, so could you please release jcabi-parent?

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 please I need a tag with this fix

**Comment by essobedo** [comment]
@yegor256 I'm stuck because of this ticket for more than a month, please create a tag it should not be too long with rultor

**Comment by yegor256** [comment]
@rultor release, tag is `0.44`

**Comment by essobedo** [comment]
@yegor256 thank you
