### ISSUE TITLE
Switch from cobertura to jacoco

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-parent#57]
Cobertura is very error-prone and slower than jacoco (cobertura needs to execute tests again, jacoco uses agent to listen to the tests being executed), so upgrading should give us more reliability and speed up builds of the projects.

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by longtimeago** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@dmarkov assign @longtimeago to this pls

**Comment by dmarkov** [comment]
> @dmarkov assign @longtimeago to this pls

@yegor256 yep, done. @longtimeago it is your task now

**Comment by dmarkov** [comment]
@krzyk many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `90842279`

**Comment by longtimeago** [comment]
@dmarkov @yegor256 here is the PR https://github.com/jcabi/jcabi-parent/pull/58

**Comment by dmarkov** [comment]
> @dmarkov @yegor256 here is the PR https://github.com/jcabi/jcabi-parent/pull/58

@longtimeago thank you, I will check it

**Comment by longtimeago** [comment]
@dmarkov assign someone else, I'm on vacation from today, can't finish the issue in time :(

**Comment by dmarkov** [comment]
> @dmarkov assign someone else, I'm on vacation from today, can't finish the issue in time :(

@longtimeago -30 points to your rating :(

**Comment by dmarkov** [comment]
> @dmarkov assign someone else, I'm on vacation from today, can't finish the issue in time :(

@longtimeago got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@prondzyn this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by prondzyn** [comment]
@dmarkov PR #59 is ready.

**Comment by dmarkov** [comment]
> @dmarkov PR #59 is ready.

@prondzyn thanks

**Comment by prondzyn** [comment]
@dmarkov please give me more time. PR is almost done. Waiting on merge.

**Comment by prondzyn** [comment]
@krzyk please close the task. PR is merged.

**Comment by krzyk** [comment]
@prondzyn you didn't add pluginManagement section for jacoco

**Comment by prondzyn** [comment]
@dmarkov I prepared PR #60 for missing jacoco in pluginManagement section as @krzyk mentioned.

**Comment by dmarkov** [comment]
> @dmarkov please give me more time. PR is almost done. Waiting on merge.

@prondzyn yes, take your time, thanks for letting me know

**Comment by prondzyn** [comment]
@krzyk please close the task now - I added missing section.

**Comment by krzyk** [comment]
@prondzyn thanks

**Comment by dmarkov** [comment]
@prondzyn I just added **30 mins** to your account, many thanks for your contribution (AP-79H96535HM877332K).. 385 hours and 19 mins spent here... +30 to your rating, your total score is [+60](http://www.netbout.com/b/35715?open=rating)

**Comment by original-brownbear** [comment]
@yegor256 can we get a release including this one ? :)
