### ISSUE TITLE
Release 0.46

### ISSUE THREAD

**Issue by original-brownbear** [jcabi/jcabi-parent#61]
@yegor256 releasing the current state would save me some time in one of our projects.
The release pipeline is broken, due to the Jacoco issues now apparently resolved here.
So a quick release saves me 15 min for a rollback and meddling with Rultor etc :)
Thanks

**Comment by mkordas** [comment]
@yegor256 please help us here

**Comment by mkordas** [comment]
@yegor256 please just invoke `@rultor release, tag is 0.46`

**Comment by yegor256** [comment]
@rultor release, tag is `0.46`

**Comment by original-brownbear** [comment]
@yegor256 thanks :)

**Comment by yegor256** [comment]
@original-brownbear please forgive the delay!

**Comment by original-brownbear** [comment]
@yegor256 np :)

**Comment by mkordas** [comment]
@yegor256 thanks!
@original-brownbear let's close this issue then :)

**Comment by original-brownbear** [comment]
@mkordas right :)
