### ISSUE TITLE
coveralls report failing due to invalid timestamp format

### ISSUE THREAD

**Issue by codejanovic** [jcabi/jcabi-parent#62]
coveralls maven plugin will fail to build when using jcabi parent, as it is not able to parse the defined `maven.build.timestamp.format` from jcabis `pom.xml`. 

to fix this issue, you need to provide a custom datefomat in coveralls plugin-configuration (as already mentioned in https://github.com/jcabi/jcabi-jdbc/pull/53)

``` xml
<plugin>
    <groupId>org.eluder.coveralls</groupId>
    <artifactId>coveralls-maven-plugin</artifactId>
    <version>4.2.0</version>
    <configuration>
        <timestampFormat>yyyy-MM-dd'T'HH:mm:ss</timestampFormat>
    </configuration>
</plugin>
```

Because so many people out there are using coveralls service I think this is a very crucial peace of information that should be made visible either in the `README.MD` or on http://parent.jcabi.com/index.html (or both)

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@codejanovic hope this helps: 8a712fe

**Comment by yegor256** [comment]
@rultor release, tag is `0.48`

**Comment by yegor256** [comment]
@codejanovic should be fine now? If so, please close the ticket

**Comment by codejanovic** [comment]
@yegor256 yep, that should solve it. thanks!
