### ISSUE TITLE
xcop

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-parent#73]
Let's add it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#73` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2325](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.49`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#73` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2355](http://www.0crat.com/u/yegor256).
