### ISSUE TITLE
Error when running xcop:  The system cannot find the file specified

### ISSUE THREAD

**Issue by fabriciofx** [jcabi/jcabi-parent#76]
I'm trying execute a `$ mvn clean install -Pqulice` and I receive this error when maven it's trying running `xcop`: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project cactoos: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "xcop": CreateProcess error=2, The system cannot find the file specified
[ERROR] around Ant part ...<exec failonerror="true" executable="xcop">... @ 18:50 in C:\Users\fbc\workspace\yegor256\cactoos\target\antrun\build-main.xml
```
`xcop` is already installed, working correctly and in my $PATH. Maybe [this](http://javafries.blogspot.com.br/2016/10/execute-failed-javaioioexception-cannot.html) could help to found a solution.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx hm... I see the problem, but don't really know how to fix it. We can't know the absolute path of `xcop` in your system. Do you have any ideas?

**Comment by fabriciofx** [comment]
@yegor256 I don't know either. Is it possible do something like a `which xop` and put it inside to maven?

**Comment by yegor256** [comment]
@fabriciofx I don't think so... try to Google, please. I'm not a Windows user(

**Comment by fabriciofx** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.4`

**Comment by fabriciofx** [comment]
Closed by #85

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#76` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by fabriciofx** [comment]
@yegor256 Is there anything wrong with 0crat? I've opened this issue and submitted a PR and haven't received any points...

**Comment by yegor256** [comment]
@g4s8 what do you think?

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-parent/issues/76#issuecomment-489402317))

@g4s8 This is what I know about this job in [C3RUBL5H9](https://www.0crat.com/p/C3RUBL5H9), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#76](https://github.com/jcabi/jcabi-parent/issues/76) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3RUBL5H9?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-parent%2376%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@fabriciofx @yegor256 this job was not added to scope, this is why no points for bug-report. See https://www.zerocracy.com/policy.html#29 https://www.zerocracy.com/policy.html#14
