### ISSUE TITLE
xcop checking files in target dir of modules in multi-module projects

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-parent#79]
The current configuration for `xcop` will only exclude the **top-most child directory named `target`**:

```xml
 <fileset dir="." id="files">
       <include name="**/*.xml"/>
       <include name="**/*.xsl"/>
       <include name="**/*.xsd"/>
       <exclude name="target/**/*"/>
       <exclude name=".idea/**/*"/>
 </fileset>
```

This causes problems in multi-module projects such as [s3auth](https://github.com/yegor256/s3auth) because it starts checking auto-generated XMLs placed in the `target` dir of submodules, such as those generated by the `surefire` plugin.

~For the moment being I'm overriding this configuration and using this as the exclude:~

```xml
<exclude name="**/target/**/*"/>
```

Scratch that, that solution does not work.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@yegor256 actually, I also had to add another exclude: `<exclude name="**/local-repo/**/*"/>`.

This tells me that `xcop` should be configurable per-project, like eg. having a config file `.xcop` in the root directory of the project. WDYT?

**Comment by yegor256** [comment]
@llorllale yes, the `.xcop` idea sounds reasonable. Please, submit it to its repo.

**Comment by yegor256** [comment]
@llorllale I guess this one should be closed, right?

**Comment by llorllale** [comment]
@yegor256 yes, closing

**Comment by fabriciofx** [comment]
@yegor256 @llorllale Is there anything wrong with 0crat? I've opened this issue and submitted a PR and haven't received any points...
