### ISSUE TITLE
Upgrade antlr4-maven-plugin to 4.7.1

### ISSUE THREAD

**Issue by fabriciofx** [jcabi/jcabi-parent#84]
When run ANTLRv4 to generate sources, if we are using the latest version (4.7) it will show to us a warning message: `ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7`.
To fix it, we need upgrade ` antlr4-maven-plugin` plugin to version `4.7.1`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@fabriciofx done in 3e89cca8

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#84` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
