### ISSUE TITLE
Rename this project to cactoos-parent (or something like that)

### ISSUE THREAD

**Issue by fabriciofx** [jcabi/jcabi-parent#86]
@yegor256 My idea is bring `jcabi-parent` to `cactoos` umbrella project. So, let's rename this project to `cactoos-parent` or something like that. WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@fabriciofx what for? This project is used in many other places, not only in Cactoos.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#86` is not assigned, can't get performer
