### ISSUE TITLE
Requires the ability to add directories or files to the antrun-plugin excludes.

### ISSUE THREAD

**Issue by zCRUSADERz** [jcabi/jcabi-parent#87]
Required optional patternset to the maven-antrun-plugin configuration, in xdoc profile.

I need this functionality to solve a problem with building a Qulice project. Now the plugin processes all `*.xml`, `*.xsd` and `*.xsl` files, excluding the `target` and `.idea` directories. In the Qulice project, directories `target` and `.idea` at the root of the project will be excluded, but the same directories in the modules will not be excluded anymore. First, it is not necessary to check the files in the modules, since they will be checked when building these modules, and secondly in the qulice project, this leads to an IOException when xcop is started, because these files are too many and cannot be passed as arguments to the command line.

> [INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for qulice 1.0-SNAPSHOT:
[INFO]
[INFO] qulice ............................................. FAILURE [  8.151 s]
[INFO] qulice-spi ......................................... SKIPPED
[INFO] qulice-checkstyle .................................. SKIPPED
[INFO] qulice-pmd ......................................... SKIPPED
[INFO] qulice-findbugs .................................... SKIPPED
[INFO] qulice-ant ......................................... SKIPPED
[INFO] qulice-maven-plugin ................................ SKIPPED
[INFO] qulice-spotbugs .................................... SKIPPED
[INFO] qulice-gradle-plugin ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.254 s
[INFO] Finished at: 2019-05-07T17:48:34+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project qulice: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "cmd": CreateProcess error=206, Имя файла или его расширение имеет слишком большую длину
[ERROR] around Ant part ...<exec failonerror="true" executable="cmd">... @ 24:53 in C:\projects\qulice\target\antrun\build-main.xml
[ERROR] -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project qulice: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "cmd": CreateProcess error=206, Имя файла или его расширение имеет слишком большую длину around Ant part ...<exec failonerror="true" executable="cmd">... @ 24:53 in C:\projects\qulice\target\antrun\build-main.xml

[log.txt](https://github.com/jcabi/jcabi-parent/files/3152264/log.txt)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.5`

**Comment by zCRUSADERz** [comment]
@yegor256 i described the problem in more detail.

**Comment by zCRUSADERz** [comment]
@yegor256 can i get points for this issue?

**Comment by yegor256** [comment]
@zCRUSADERz thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#87` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@zCRUSADERz this job was not in scope, that's why no points, sorry
