### ISSUE TITLE
Profile xdoc dont work properly on windows.

### ISSUE THREAD

**Issue by zCRUSADERz** [jcabi/jcabi-parent#88]
#### jcabi-parent 0.49.4
-------
Profile xdoc starts a xcop without a `--license` argument on Windows.

To reproduce you need:
- Windows
- Installed xcop

Steps to reproduce:
- Clone this repository
- Delete comment with license from pom.xml
- run `mvn -Pqulice clean install`
- run `xcop --license LICENSE.txt pom.xml`
- compare the results

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by zCRUSADERz** [comment]
It fixed in #90.

**Comment by zCRUSADERz** [comment]
@yegor256 can i get points for this issue?

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#88` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
