### ISSUE TITLE
xcop exclude target everywhere

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-parent#91]
Let's exclude it in child modules too

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.8`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#91` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
