### ISSUE TITLE
Nexus staging maven plugin fails on timeout quite often

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-parent#98]
Deploy often fails because of timeout in Nexus staging maven plugin, the standard timeout is 5 minutes, Sonatype sometimes can't process new artifact in 5 minutes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it's fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#98` is not assigned, can't get performer
